defaultEntryPoints = ["http", "https"]
[web]
address = ":8080"
  [web.auth.basic]
  users = ["admin:$apr1$mQWcgmLG$iaw/u7NY1fEjijx0yCrT.."]
  # admin:$apr1$mQWcgmLG$iaw/u7NY1fEjijx0yCrT..

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
    email = "mokikz@web.de"
    storage = "acme.json"
    entryPoint = "https"
    onHostRule = true
    onDemand = false
